name: Check commands
on: [push]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: mcbeet/check-commands@v1
        with:
          source: .
          minecraft: "1.19"
          stats: true
          version: '0.52.2'
